### ISSUE TITLE
[Improvement/Bug] Allow in config to change if the plugin warns about inefficient placeholders

### ISSUE THREAD

**Issue by ryzech** [NEZNAMY/TAB-Bridge#27]
Currently every time a placeholder refresh is over a certain threshold in time, it sends a warn message to the console, this can fill up log files very quickly, and in my case i'm not worried about the time it takes as it does work regardless.

![image](https://github.com/NEZNAMY/TAB-Bridge/assets/61711965/b0d4aa1f-f9f2-43c4-8b2a-13db2a26e5c0)

I'm not 100% certain where this is in code, but it should be easy enough to only display if it's enabled in a config file (which would also have to be created.)

**Comment by NEZNAMY** [comment]
The problem is that if I don't do this, people will come crying that the plugin isn't refreshing placeholders. Since a command like /tab cpu is not available on the bridge, you have no way to know which placeholder is killing it. I spent days trying to figure it out for incompetent users in a ticket when this wasn't a thing, only to get them back in a few days later because they added the faulty placeholder back to their configs. You can use a plugin like ConsoleSpamFix to filter out these messages if you have no interest in getting your plugins fixed.

**Comment by ryzech** [comment]
I see, that makes sense so fair enough, thank you!
